{
 "title": "Zulip",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Server version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zulip_server{info=\"zulip_version\"})"
    }
   ]
  },
  {
   "title": "Users: Bots",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((zulip_user_bots_total/zulip_user_total) * 100)"
    }
   ]
  },
  {
   "title": "User: % Human",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((zulip_user_total-zulip_user_bots_total)/zulip_user_total) * 100)"
    }
   ]
  },
  {
   "title": "Users: Admins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(zulip_user_admins_total)" }
   ]
  },
  {
   "title": "Users Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(zulip_user_total)" }
   ]
  },
  {
   "title": "User: Deactivated ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zulip_user_total - zulip_user_active_total)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total Subscription",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(zulip_stream_total)" }
   ]
  },
  {
   "title": "Weelky message",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zulip_stream_stream_weekly_traffic) by (stream)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Stream: Public",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zulip_stream_is_web_public != 0"
    }
   ]
  }
 ]
}