apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zulip-exporter
  labels:
    app: zulip-exporter
spec:
  selector:
    matchLabels:
      app: zulip-exporter
  endpoints:
    - port: metrics
      honorLabels: true
